spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecm?useTimezone=true&serverTimezone=UTC
    username: dev1
    password: dev1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update